### PR TITLE
To support Will Message Feature

### PR DESCRIPTION
**Pull request by shendongsd**
[#69 ](https://github.com/apache/rocketmq-mqtt/issues/69) To support Will Message Feature

### CODE REVIEW

**Comment by tianliuliu** [comment]
please fix the Travis CI check, thx

**Comment by pingww** [comment]
Could you write a detailed design proposal

**Comment by zongtanghu** [comment]
@shendongsd Could you modify this pr as other members' suggetions!

**Comment by zongtanghu** [comment]
I see this pr's code has some codes' conflicts, you can rebase it. And you should link your supporting will messaging design doc here! @shendongsd

**Pull request closed without merging**
