### PR TITLE
[ISSUE #70]Add retained message

### LINKED ISSUE #70: To support Retain Message Feature
**Retain Message** are also a feature of the MQTT 3.1.1 protocol that is not supported in our current release and we plan to discuss implementation solutions for this protocol feature.

### PR DESCRIPTION
**Pull request by YYYYWD**
close #70 
Implement retained messages via kv store

### CODE REVIEW

**Comment by YYYYWD** [comment]
#70

**Comment by DongyuanPan** [comment]
please fix travis ci

**Comment by pingww** [comment]
add some unit tests

**Comment by DongyuanPan** [comment]
The KV will be removed and the code can be submitted to the Develop branch based on the state machine

**Comment by ShannonDing** [comment]
close due to #131.

**Pull request closed without merging**
